name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    name: Lint, Build, Test
    strategy:
      fail-fast: false
      matrix:
        version: [14, 16, 18]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.version }}
          cache: npm
      - name: Install npm dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Test
        run: npm test

  coverage:
    name: Upload coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: npm
      - name: Install npm dependencies
        run: npm ci
      - name: Test
        run: npm run coverage
      - name: Code Climate Coverage Action
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: cfbbbb9db607b3c503fe3af721ac5c8efc801024a8fc8d7ea6759e11a54396bd
        with:
          coverageCommand: npm run coverage
          coverageLocations: |
            ${{github.workspace}}/coverage/lcov.info:lcov
